"""Add OAuth clients and authorization codes

Revision ID: 671ffe10a0a5
Revises: ffb1a560b760
Create Date: 2025-11-14 22:48:07.440670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '671ffe10a0a5'
down_revision: Union[str, Sequence[str], None] = 'ffb1a560b760'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
