"""Add refresh_token_hash column for rotation

Revision ID: 72c818a3c167
Revises: d7a90169b2b5
Create Date: 2025-11-15 20:43:18.730926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '72c818a3c167'
down_revision: Union[str, Sequence[str], None] = 'd7a90169b2b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('refresh_token_hash', sa.String(length=128), nullable=False))
    op.alter_column('sessions', 'session_token',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=1024),
               nullable=True)
    op.alter_column('sessions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('sessions', 'revoked',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index(op.f('idx_session_token'), table_name='sessions')
    op.drop_constraint(op.f('sessions_refresh_token_key'), 'sessions', type_='unique')
    op.create_index('idx_session_refresh_hash', 'sessions', ['refresh_token_hash'], unique=False)
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_index(op.f('ix_sessions_refresh_token_hash'), 'sessions', ['refresh_token_hash'], unique=True)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.drop_column('sessions', 'refresh_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('refresh_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_refresh_token_hash'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_index('idx_session_refresh_hash', table_name='sessions')
    op.create_unique_constraint(op.f('sessions_refresh_token_key'), 'sessions', ['refresh_token'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_session_token'), 'sessions', ['session_token'], unique=False)
    op.alter_column('sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('sessions', 'revoked',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('sessions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('sessions', 'session_token',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('sessions', 'refresh_token_hash')
    # ### end Alembic commands ###
